# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Run Python commands
      run: |
        pip install --upgrade pip
        python3.10 -m venv env
        source env/bin/activate
        echo "VIRTUAL ENV:" $VIRTUAL_ENV
        deactivate
    - name: Set up VENV
      run: |
        python3 -m venv test_venv
        source test_venv/bin/activate
        echo "VIRTUAL ENV:" $VIRTUAL_ENV
        deactivate
    - name: Test script
      run: |
        bash test.sh
    - name: Test makefile by setting SHELL
      run: |
        export SHELL=/usr/bin/bash && make all && unset SHELL
    - name: Test makefile with env SHELL
      run: |
        SHELL='/usr/bin/bash' make all
    - name: Test makefile with bash shell
      shell: bash
      run: |
        make all
    - name: Test makefile
      run: |
        make all
